// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_transaction is a generated GoMock package.
package mock_transaction

import (
	sql "database/sql"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockTxRepo is a mock of TxRepo interface
type MockTxRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTxRepoMockRecorder
}

// MockTxRepoMockRecorder is the mock recorder for MockTxRepo
type MockTxRepoMockRecorder struct {
	mock *MockTxRepo
}

// NewMockTxRepo creates a new mock instance
func NewMockTxRepo(ctrl *gomock.Controller) *MockTxRepo {
	mock := &MockTxRepo{ctrl: ctrl}
	mock.recorder = &MockTxRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTxRepo) EXPECT() *MockTxRepoMockRecorder {
	return m.recorder
}

// Transaction mocks base method
func (m *MockTxRepo) Transaction(f func(*sql.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction
func (mr *MockTxRepoMockRecorder) Transaction(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockTxRepo)(nil).Transaction), f)
}
