use dojo_api;

SET NAMES utf8mb4;

INSERT INTO collection_item (id, name, rarity) VALUES ("test1","テスト1",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test2","test2",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test3","test3",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test4","test4",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test5","test5",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test6","test6",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test7","test7",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test8","test8",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test9","test9",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test10","test10",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test11","test11",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test12","test12",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test13","test13",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test14","test14",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test15","test15",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test16","test16",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test17","test17",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test18","test18",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test19","test19",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test20","test20",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test21","test21",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test22","test22",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test23","test23",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test24","test24",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test25","test25",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test26","test26",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test27","test27",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test28","test28",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test29","test29",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test30","test30",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test31","test31",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test32","test32",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test33","test33",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test34","test34",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test35","test35",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test36","test36",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test37","test37",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test38","test38",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test39","test39",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test40","test40",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test41","test41",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test42","test42",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test43","test43",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test44","test44",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test45","test45",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test46","test46",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test47","test47",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test48","test48",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test49","test49",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test50","test50",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test51","test51",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test52","test52",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test53","test53",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test54","test54",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test55","test55",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test56","test56",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test57","test57",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test58","test58",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test59","test59",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test60","test60",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test61","test61",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test62","test62",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test63","test63",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test64","test64",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test65","test65",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test66","test66",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test67","test67",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test68","test68",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test69","test69",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test70","test70",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test71","test71",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test72","test72",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test73","test73",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test74","test74",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test75","test75",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test76","test76",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test77","test77",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test78","test78",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test79","test79",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test80","test80",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test81","test81",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test82","test82",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test83","test83",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test84","test84",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test85","test85",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test86","test86",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test87","test87",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test88","test88",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test89","test89",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test90","test90",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test91","test91",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test92","test92",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test93","test93",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test94","test94",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test95","test95",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test96","test96",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test97","test97",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test98","test98",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test99","test99",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test100","test100",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test101","test101",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test102","test102",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test103","test103",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test104","test104",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test105","test105",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test106","test106",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test107","test107",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test108","test108",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test109","test109",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test110","test110",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test111","test111",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test112","test112",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test113","test113",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test114","test114",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test115","test115",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test116","test116",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test117","test117",3);
INSERT INTO collection_item (id, name, rarity) VALUES ("test118","test118",1);
INSERT INTO collection_item (id, name, rarity) VALUES ("test119","test119",2);
INSERT INTO collection_item (id, name, rarity) VALUES ("test120","test120",3);

INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test1",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test2",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test3",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test4",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test5",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test6",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test7",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test8",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test9",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test10",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test11",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test12",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test13",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test14",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test15",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test16",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test17",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test18",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test19",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test20",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test21",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test22",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test23",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test24",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test25",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test26",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test27",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test28",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test29",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test30",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test31",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test32",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test33",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test34",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test35",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test36",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test37",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test38",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test39",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test40",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test41",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test42",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test43",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test44",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test45",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test46",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test47",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test48",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test49",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test50",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test51",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test52",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test53",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test54",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test55",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test56",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test57",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test58",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test59",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test60",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test61",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test62",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test63",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test64",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test65",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test66",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test67",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test68",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test69",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test70",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test71",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test72",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test73",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test74",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test75",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test76",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test77",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test78",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test79",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test80",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test81",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test82",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test83",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test84",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test85",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test86",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test87",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test88",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test89",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test90",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test91",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test92",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test93",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test94",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test95",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test96",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test97",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test98",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test99",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test100",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test101",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test102",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test103",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test104",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test105",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test106",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test107",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test108",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test109",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test110",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test111",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test112",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test113",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test114",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test115",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test116",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test117",1);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test118",3);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test119",2);
INSERT INTO gacha_probability (collection_item_id, ratio) VALUES ("test120",1);
