// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mock_ranking is a generated GoMock package.
package mock_ranking

import (
	user "20dojo-online/pkg/server/domain/model/user"
	myerror "20dojo-online/pkg/server/interface/myerror"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRankingUseCase is a mock of RankingUseCase interface
type MockRankingUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRankingUseCaseMockRecorder
}

// MockRankingUseCaseMockRecorder is the mock recorder for MockRankingUseCase
type MockRankingUseCaseMockRecorder struct {
	mock *MockRankingUseCase
}

// NewMockRankingUseCase creates a new mock instance
func NewMockRankingUseCase(ctrl *gomock.Controller) *MockRankingUseCase {
	mock := &MockRankingUseCase{ctrl: ctrl}
	mock.recorder = &MockRankingUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRankingUseCase) EXPECT() *MockRankingUseCaseMockRecorder {
	return m.recorder
}

// GetUsersByHighScore mocks base method
func (m *MockRankingUseCase) GetUsersByHighScore(startNum int32) ([]*user.UserL, *myerror.MyErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByHighScore", startNum)
	ret0, _ := ret[0].([]*user.UserL)
	ret1, _ := ret[1].(*myerror.MyErr)
	return ret0, ret1
}

// GetUsersByHighScore indicates an expected call of GetUsersByHighScore
func (mr *MockRankingUseCaseMockRecorder) GetUsersByHighScore(startNum interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByHighScore", reflect.TypeOf((*MockRankingUseCase)(nil).GetUsersByHighScore), startNum)
}
