// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	user "20dojo-online/pkg/server/domain/model/user"
	sql "database/sql"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUserRepository is a mock of UserRepository interface
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// SelectUserByUserID mocks base method
func (m *MockUserRepository) SelectUserByUserID(userID string) (*user.UserL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUserByUserID", userID)
	ret0, _ := ret[0].(*user.UserL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUserByUserID indicates an expected call of SelectUserByUserID
func (mr *MockUserRepositoryMockRecorder) SelectUserByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUserByUserID", reflect.TypeOf((*MockUserRepository)(nil).SelectUserByUserID), userID)
}

// SelectUserByAuthToken mocks base method
func (m *MockUserRepository) SelectUserByAuthToken(userID string) (*user.UserL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUserByAuthToken", userID)
	ret0, _ := ret[0].(*user.UserL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUserByAuthToken indicates an expected call of SelectUserByAuthToken
func (mr *MockUserRepositoryMockRecorder) SelectUserByAuthToken(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUserByAuthToken", reflect.TypeOf((*MockUserRepository)(nil).SelectUserByAuthToken), userID)
}

// SelectUsersByHighScore mocks base method
func (m *MockUserRepository) SelectUsersByHighScore(limit, start int32) ([]*user.UserL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUsersByHighScore", limit, start)
	ret0, _ := ret[0].([]*user.UserL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUsersByHighScore indicates an expected call of SelectUsersByHighScore
func (mr *MockUserRepositoryMockRecorder) SelectUsersByHighScore(limit, start interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUsersByHighScore", reflect.TypeOf((*MockUserRepository)(nil).SelectUsersByHighScore), limit, start)
}

// InsertUser mocks base method
func (m *MockUserRepository) InsertUser(user *user.UserL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUser indicates an expected call of InsertUser
func (mr *MockUserRepositoryMockRecorder) InsertUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockUserRepository)(nil).InsertUser), user)
}

// UpdateUserByUser mocks base method
func (m *MockUserRepository) UpdateUserByUser(user *user.UserL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserByUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserByUser indicates an expected call of UpdateUserByUser
func (mr *MockUserRepositoryMockRecorder) UpdateUserByUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserByUser", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserByUser), user)
}

// UpdateUserByUserInTx mocks base method
func (m *MockUserRepository) UpdateUserByUserInTx(user *user.UserL, tx *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserByUserInTx", user, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserByUserInTx indicates an expected call of UpdateUserByUserInTx
func (mr *MockUserRepositoryMockRecorder) UpdateUserByUserInTx(user, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserByUserInTx", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserByUserInTx), user, tx)
}
